### PR TITLE
369 dynamic docker deploy fails on the last container

### LINKED ISSUE #369: Dynamic docker deploy fails on the last container

### PR DESCRIPTION
**Pull request by fkengun**
Changes in this PR:

- Fix the deadlock bug in dynamic deployment
- Build and install ChronoLog in parallel
- Add a script specific for PEARC'25 with Grafana
- Fix a file naming typo

### CODE REVIEW

File: CI/docker/dynamic_deploy.sh [hunk 1]
```diff
@@ -189,15 +153,18 @@ done
 for i in $(seq 1 $NUM_CONTAINERS); do
     docker exec -it chronolog-c1 bash -c "echo c$i >> ~/chronolog_install/Release/conf/hosts_clients"
 done
+for i in $(seq 1 $NUM_CONTAINERS); do
+    docker exec -it chronolog-c1 bash -c "echo c$i >> ~/chronolog_install/Release/conf/hosts_all"
+done
 
 # Force concretize and install dependencies in case of changes
-docker exec -it chronolog-c1 bash -c "cd ~/chronolog_repo && source ~/spack/share/spack/setup-env.sh && spack env activate . && cd deploy && spack concretize --force"
+docker exec -it chronolog-c1 bash -c "cd ~/chronolog_repo && source ~/spack/share/spack/setup-env.sh && spack env activate . && spack concretize --force"
```
Comment (ibrodkin) [inline CI/docker/dynamic_deploy.sh]: Don't we have to follow "spack env activate" with "spack install " ?

File: CI/docker/dynamic_deploy.sh [hunk 2]
```diff
@@ -189,15 +153,18 @@ done
...
 
 # Rebuild ChronoLog
-docker exec -it chronolog-c1 bash -c "cd ~/chronolog_repo && source ~/spack/share/spack/setup-env.sh && spack env activate . && cd deploy && ./single_user_deploy.sh -b -l ~/chronolog_install"
+docker exec -it chronolog-c1 bash -c "cd ~/chronolog_repo && source ~/spack/share/spack/setup-env.sh && spack env activate . && cd build && make -j"
```
Comment (ibrodkin) [inline CI/docker/dynamic_deploy.sh:164]: "cmake -DCMAKE_BUILD_TYPE=Release"    before "make -j"

File: CI/docker/dynamic_deploy.sh (hunk 1 above)
Comment (fkengun) [reply CI/docker/dynamic_deploy.sh]: > Don't we have to follow "spack env activate" with "spack install " ?

Since the image is expected to have a complete spack env with all dependencies installed, `spack env activate .` is enough to load all of them.

File: CI/docker/dynamic_deploy.sh (hunk 2 above)
Comment (fkengun) [reply CI/docker/dynamic_deploy.sh:164]: > "cmake -DCMAKE_BUILD_TYPE=Release" before "make -j"

The initial step of `cmake -DCMAKE_BUILD_TYPE=Release ..` has been done during the building of the image. The `make -j` is just for building the latest codes.

File: CI/docker/dynamic_deploy.sh (hunk 1 above)
Comment (ibrodkin) [reply CI/docker/dynamic_deploy.sh]: I suggest we still do "spack install" if everything is installed and concretized correctly than this call would take no time at all , but if something is off , you want it to be called here, not proceed

**Review by ibrodkin — APPROVED** [review]
