### PR TITLE
360 issues in story chunk

### LINKED ISSUE #360: Issues in StoryChunk implementation
Recently added StoryChunk Unit tests ( #327  ) identified the following bugs in StoryChunk implementation. they need to be fixed.
 

1. When we insert a true duplicate event, insert events rejects the duplicate correctly but the function call returns 1, it should return 0 to signal failure of inserting (linked to StoryChunk_TestInsertEvent, testDuplicateKeyCombinations)
2. When we try to insert a log event with a different storyid as compared to the storyid of the chunk, it should get rejected (linked to StoryChunk_TestInsertEvent, testIncorrectEventId)
3. Add a check for handling nullptr in payload of log events at creation time (linked to StoryChunk_TestInsertEvent, testNullEvent)
4. When merging an out of time bounds chunk to a master chunk, the rejected events in the other chunk should not be deleted, they should just get rejected and remain in the other chunk (linked to StoryChunk_TestMergeEvents, testMergeOutsideWindow)
5. When we try to call merge events on a chunk with a time stamp after the end of that chunk, it should get rejected and not still merge (linked to StoryChunk_TestMergeEvents, testMergeStartTimeAfterEnd). Incorrect story id in merge events should be rejected similar to item 2 (linked to StoryChunk_TestMergeEvents, testIncorrectStoryId)

### PR DESCRIPTION
**Pull request by ibrodkin**
Changes in StoryChunk to fix a few issues exposed by the StoryChunk Unit Tests 
Changes in StorychunkUnitTest code where corrections/additions were needed to reflect expected StoryChunk behavior .

### CODE REVIEW

**Review by iameneko — APPROVED** [review]

File: test/unit/StoryChunkTest.cpp [hunk 1]
```diff
@@ -630,19 +636,31 @@ TEST(StoryChunk_TestMergeEvents, testMixedChunkMerge)
 }
 
 
-// try calling merge events with a merge start time as after end time of the chunk
+// try calling merge events with a merge start_merge value passed being earlier than startime of both chunks or later than end time of both
+// expected behavior is that only the events that are within the master chunk boundaries will be merged from the other_chunk into the master chunk
 // BUG -> should not merge after end time of the chunk, should have got rejected
```
Comment (fkengun) [inline test/unit/StoryChunkTest.cpp]: should we remove this line if this bug has been fixed?

Comment (ibrodkin) [reply test/unit/StoryChunkTest.cpp]: comment removed

**Review by fkengun — APPROVED** [review]
